config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'restaurants#index'
  resources :restaurants do
    # CRUD routes
    resources :reviews, only: [:create]
    # Non-CRUD routes
    collection do
      get :top
    end
    member do
      get :chef
    end
  end
  resources :reviews, only: [:destroy]
  # get '/restaurants/top', to: 'restaurants#top', as: :top_restaurants
  # get '/restaurants/:id/chef', to: 'restaurants#chef', as: :chef_restaurant

end

# Non-CRUD Routes
# collection -> about all restaurants (aka no ID)
# member     -> about a specific restaurant (aka need an ID)

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  # associations
  has_many :reviews, dependent: :destroy # restaurant.reviews
  belongs_to :user
  # validations
  validates :name, presence: true, uniqueness: true
end

# dependent: :destroy
# if we delete vincent's restaurant, it will destroy all of his reviews

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant # review.restaurant
  validates :content, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit::Authorization

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :top, :chef]

  # '/restaurants/top'
  def top
    @restaurants = Restaurant.where(rating: 5)
  end

  # '/restaurants/1/chef'
  def chef
    @restaurant = Restaurant.find(params[:id])
  end

  # '/restaurants'
  def index
    @restaurants = policy_scope(Restaurant)


    # @bookings = current_user.bookings
    # render 'index.html.erb'
  end

  # '/restaurants/1'
  def show
    @restaurant = Restaurant.find(params[:id])
    # this is for the form
    @review = Review.new
    # render 'show.html.erb'
    authorize @restaurant
  end

  # '/restaurants/new'
  def new
    # this instance variable is JUST for the form
    @restaurant = Restaurant.new
    authorize @restaurant
  end

  # we cant access from a URL. The form is sending the data here (/restaurants)
  # THIS DOES NOT HAVE A VIEW
  def create
    # we need to create our instance with our STRONG params
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user = current_user
    authorize @restaurant
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      # show the form with the restaurant that didnt save (not a brand new one)
      render 'new', status: :unprocessable_entity
    end
  end

  # '/restaurants/1/edit'
  def edit
    # this instance variable is JUST for the form
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
  end

  def update
    # load the the instacne i want to update
    @restaurant = Restaurant.find(params[:id])
    # update the instance with the strong_params
    authorize @restaurant
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  # we cant access this one in the URL, but a link can with a delete method
  def destroy
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
    @restaurant.destroy
    redirect_to restaurants_path, status: :see_other
  end

  private

  def restaurant_params
    # we are whitelisting the attributes a user can give us
    params.require(:restaurant).permit(:name, :address, :rating, :category, :opening_date)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  # THE "NEW" IS NOT MOVED TO RESTAURANTS#SHOW
  # '/restaurants/22/reviews/new'
  # def new
  #   # BOTH for the form
  #   @review = Review.new
  #   @restaurant = Restaurant.find(params[:restaurant_id])
  # end

  # post '/restaurants/22/reviews' (no view)
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      json_sent_to_js_controller = {
        form: render_to_string(partial: "reviews/form", locals: { review: Review.new, restaurant: @restaurant }, formats: [:html]),
        review: render_to_string(partial: "reviews/review", locals: { review: @review }, formats: [:html])
      }
      respond_to do |format|
        format.html { redirect_to restaurant_path(@restaurant) }
        format.json { render json: json_sent_to_js_controller, status: :created }
      end
    else
      # only send the form if the review didn't save
      json_sent_to_js_controller = {
        form: render_to_string(partial: "reviews/form", locals: { review: @review, restaurant: @restaurant }, formats: [:html])
      }
      respond_to do |format|
        format.html { render 'restaurants/show', status: :unprocessable_entity }
        format.json { render json: json_sent_to_js_controller, status: :created }
      end
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant), status: :see_other
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restaurants1638</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restaurants1638</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render "shared/flashes" %>
    <div class="container mt-3">
      <div class="row justify-content-center">
        <div class="col col-sm-8 col-md-6">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/restaurants/_card.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(http://source.unsplash.com/featured/?<%= restaurant.category.downcase %>&<%= rand(1000) %>)">
  <%= link_to restaurant.name, restaurant_path(restaurant), class: 'text-decoration-none text-white' %>
</div>

app/views/restaurants/_form.html.erb
<!-- Form builder will: -->
<!-- add the action (/restaurants) -->
<!-- add the method (post) -->
<!-- adds the authenticity token -->
<!-- grouping all of our attributes inside of one hash -->
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :rating %>
  <%= f.input :category %>
  <%= f.input :opening_date,
            as: :string,
            input_html: { data: { controller: "datepicker" }, class: 'custom-class' } %>
  <%= f.submit class: 'btn btn-primary mt-2' %>
<% end %>

app/views/restaurants/_side_info.html.erb
<p class="fw-lighter opacity-75">
  <i class="fas fa-map-pin"></i><span class='ms-2'><%= @restaurant.address %></span>
</p>
<p class="fw-lighter opacity-75">
  <% rand(2..5).times do %>
    <i class="fas fa-dollar-sign"></i>
  <% end %>
</p>
<p class="fw-lighter opacity-75">
  <i class="fas fa-utensils"></i><span class='ms-2'><%= @restaurant.category %></span>
</p>
<div class="d-flex">
  <!-- edit and delete here-->
  <p>
    <% if policy(@restaurant).edit? %>
      <%= link_to edit_restaurant_path(@restaurant), class: 'text-dark text-decoration-none' do %>
        <i class="fas fa-pencil-alt mx-1"></i>
      <% end %>
    <% end %>
    <% if policy(@restaurant).destroy? %>
      <%= link_to restaurant_path(@restaurant), class: 'text-dark text-decoration-none', data: { turbo_method: :delete, turbo_confirm: "Do you want to delete #{@restaurant.name}" } do %>
        <i class="fas fa-trash mx-1"></i>
      <% end %>
    <% end %>
  </p>
</div>

app/views/restaurants/chef.html.erb
<div class="container">
  <h1>Chef <%= @restaurant.chef_name %></h1>
  <p><%= @restaurant.name %></p>
  <%= link_to 'Back', restaurant_path(@restaurant), class: 'btn btn-light'  %>
</div>

app/views/restaurants/edit.html.erb
<div class="container">
  <h1>Edit Restaurant</h1>
  <%= render 'restaurants/form' %>
</div>

app/views/restaurants/index.html.erb
<div class="container mt-3">
  <div class="d-flex justify-content-between align-items-center">
    <h1>Restaurants</h1>
    <%= link_to new_restaurant_path, class: 'text-dark text-decoration-none' do %>
      <i class="fa-solid fa-plus"></i>
    <% end %>
  </div>
  <div class="cards">
    <% @restaurants.each do |restaurant| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(http://source.unsplash.com/featured/?<%= restaurant.category.downcase %>&<%= rand(1000) %>)">
        <%= link_to restaurant.name, restaurant_path(restaurant), class: 'text-decoration-none text-white' %>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <h1>Add Restaurant</h1>
  <%= render 'restaurants/form' %>
</div>

app/views/restaurants/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(http://source.unsplash.com/featured/?<%= @restaurant.category.downcase %>&<%= rand(1000) %>/800x333);">
  <div class="container">
  </div>
</div>
<div class="container mt-2">
  <div class="row justify-content-around">
    <div class="col-12 col-sm-8">
      <p>
        <%= link_to '< Restaurants', restaurants_path, class: 'btn-light opacity-25 text-decoration-none' %>
      </p>
      <div class="d-flex align-items-center">
        <h1 class="m-0"><%= @restaurant.name %></h1>
        <p class="m-0 ms-2" style="font-size: 0.8em">
          <% @restaurant.rating.times do %>
            <i class="fas fa-star"></i>
          <% end %>
          <% (5 - @restaurant.rating).times do %>
            <i class="far fa-star"></i>
          <% end %>
        </p>
      </div>
      <p class="fw-lighter opacity-75 mt-2"><%= Faker::Restaurant.description  %></p>
      <h3>Reviews</h3>
      <div data-controller="insert-in-list">
        <button class="btn btn-light" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
          Leave a Review
        </button>
        <div class="collapse" id="collapseExample">
          <div class="card card-body">
            <!-- <form action="" data-insert-in-list-target="form" data-action="submit->insert-in-list#send"></form> -->
            <%= render 'reviews/form', review: @review, restaurant: @restaurant %>
          </div>
        </div>
        <div class="reviews" data-insert-in-list-target="reviews">
          <% @restaurant.reviews.order(created_at: :desc).each do |review| %>
            <%= render 'reviews/review', review: review %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-12 col-sm-4 mt-5">
      <%= render 'restaurants/side_info' %>
    </p>
  </div>
</div>

app/views/restaurants/top.html.erb
<div class="container mt-3">
  <div class="d-flex justify-content-between align-items-center">
    <h1>Top Restaurants</h1>
    <%= link_to new_restaurant_path, class: 'text-dark text-decoration-none' do %>
      <i class="fa-solid fa-plus"></i>
    <% end %>
  </div>
  <div class="cards">
    <% @restaurants.each do |restaurant| %>
      <%= render 'restaurants/card', restaurant: restaurant %>
    <% end %>
  </div>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [restaurant, review], data: { insert_in_list_target: 'form', action: "submit->insert-in-list#send" } do |f| %>
  <%= f.input :content, label: false, input_html: { data: { insert_in_list_target: 'input'  }} %>
  <%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

app/views/reviews/_review.html.erb
<p class="my-3"><i class="fa-solid fa-quote-left fa-2x me-2"></i><%= review.content %></p>

app/views/reviews/new.html.erb
<div class="container">
  <h1>Add Review for <%= @restaurant.name %></h1>
  <!-- add the action ( post /restaurants/22/reviews) -->
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.submit class: 'btn btn-primary mt-2' %>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <i class="fas fa-utensils"></i>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Restaurants", restaurants_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Top Restaurants", top_restaurants_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/#{current_user.username}", class: "avatar", alt: "dropdown menu" %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Restaurants", restaurants_path, class: "dropdown-item" %>
              <%= link_to "Top Restaurants", top_restaurants_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>